

export const SELECTED_VIDEO_START = "SELECTED_VIDEO_START";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";
export const SELECTED_VIDEO_CLEANUP = "SELECTED_VIDEO_CLEANUP";