

export const VIDEO_LISTING_START = "VIDEO_LISTING_START";
export const VIDEO_LISTING_SUCCESS = "VIDEO_LISTING_SUCCESS";
export const VIDEO_LISTING_FAIL = "VIDEO_LISTING_FAIL";
export const VIDEO_LISTING_CLEANUP = "VIDEO_LISTING_CLEANUP";